### PR TITLE
fix: tweak header and pager in print view

### LINKED ISSUE #227: Header is overlapping with contents in print view
[Issuehunt badges](https://issuehunt.io/r/egoist/docute/issues/227)

@kevgathuku 

Thank you for your last print style PR.

I found a bug:

If there's more than one page, page 2, 3, 4's header will override part of the content.

Can you also hide `.Header` and `.prev-next-links` in print style?

Thanks. ❤️

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Sponsors (Total: $40.00)

- [issuehunt issuehunt](https://issuehunt.io/u/issuehunt) ($40.00)

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/egoist/docute/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

### PR DESCRIPTION
**Pull request by chanjsq**
Fixes #227

### CODE REVIEW

**Comment by egoist** [comment]
屏幕快照 2019-06-13 下午10 51 19

the first page has a weird top padding.

**Comment by chanjsq** [comment]
I removed the weird top padding by reducing the `padding-top` of `.Main` by `--header-height`.

**Comment by egoist** [comment]
hmm I think there should be no padding at all?

**Comment by chanjsq** [comment]
Yes, using `padding-top: 0` is better:



I will fix this.

**Comment by chanjsq** [comment]
Done. The top padding is now completely removed.

**Comment by egoist** [comment]
welp maybe we can unset `position: fixed` for header, it's weird if we don't show header at all 😅

**Comment by chanjsq** [comment]
Good solution. 👍

**Comment by chanjsq** [comment]
A little more discussion: should `.header-nav` hide or not?

**Comment by egoist** [comment]
it's fine to keep it I guess, as long as it doesn't break anything.

**Comment by chanjsq** [comment]
I think `.header-nav` can be removed, because the header nav holds commonly used tools, e.g. search bar, help buttons, notice buttons, etc.

But I also agree with your thoughts.

I will keep it.

**Comment by egoist** [comment]
we do have a [search bar](https://github.com/egoist/docute/blob/master/src/plugins/search/SearchBar.vue), it should be hidden then

**Comment by egoist** [comment]
btw, do you actually print the PDF in papers or just need the PDF file? header nav will still be useful if you're viewing the PDF file.

**Comment by chanjsq** [comment]
Both. When making PDFs, it looks nice. But when printing in papers, it used too much papers, because the margins and the line height are too large. It can be optimized, but my design sense is poor.

**Comment by chanjsq** [comment]
Another non-topic discussion: when using projector, the text is too small to be seen. I often use `command` + `+` to increase the text size. 🤣

**Pull request merged**
