### PR TITLE
feat: improve css in print view

### LINKED ISSUE #215: Add Print Style
I often print the docs in docute by printer. But it also print the burger icon and the sidebar. I need to hide them when I print the docs. Could you please add this feature? Thanks. Love you, egoist. 💖

### PR DESCRIPTION
**Pull request by kevgathuku**
Fixes #215

Print view after applying changes in this PR:
image

### CODE REVIEW

**Comment by egoist** [comment]
Can you remove the left and right margin as well? seems we don't need that in print view

**Comment by kevgathuku** [comment]
Sure. I'll fix that too @egoist

**Comment by kevgathuku** [comment]
I've removed the margins. Here's how it looks now cc @egoist 

image

**Comment by egoist** [comment]
the margin in header in unnecessary too, maybe we don't even need the header? (@chanjsq)

**Comment by egoist** [comment]
Maybe we should show header nav in print view.

**Comment by kevgathuku** [comment]
> the margin in header in unnecessary too, maybe we don't even need the header? (@chanjsq)

I've removed the left margin in the header and updated the image. Is this the header margin you meant?

**Comment by kevgathuku** [comment]
Nice. It's looking much better now 🚀 
Thanks @egoist

**Pull request merged**
