### PR TITLE
Add service-mocker to users list

### PR DESCRIPTION
**Pull request by idiotWu**
Aha, it's [us](https://github.com/service-mocker/service-mocker) 🎉

### CODE REVIEW

**Comment by egoist** [comment]
the tip in orange color looks fantastic, we need to add adjust the current tips 😃 maybe `p.warning` `p.danger` `p.tip`

**Comment by idiotWu** [comment]
We stole the orange color from [MDN](https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorker) 😆

**Comment by egoist** [comment]
Done https://docute.js.org/#/home?id=css-helpers 😂

**Comment by idiotWu** [comment]
It makes me think of the traffic lights somehow 😂

**Comment by idiotWu** [comment]
@egoist I think the opacity value in `.danger` is a little too high 🤔 . In our docs, we are using `0.1` for the yellow one but `0.05` for the red, as the red color is much outstanding than yellow.

**Comment by idiotWu** [comment]
um...what about this pallet:

wx20170120-204250

with lightness of `96%` `96%` `97%` in HSL color space.

**Pull request merged**
