### PR TITLE
Set router mode through config

### LINKED ISSUE #49: Support history mode
If you're using github pages, you can use `404.html` together with `index.html` to simulate a history-mode app (redirect 404.html to index.html), what we need to change is to make docute update `location.hash` instead `query.id` in history mode

### PR DESCRIPTION
**Pull request by znck**
Fix #49 

This would make router history mode opt in.

### CODE REVIEW

**Comment by egoist** [comment]
[here](https://github.com/znck/docute/blob/master/src/views/Page.vue#L113-L115) also needs changes, resources are fetched from relative path now.

**Comment by znck** [comment]
URL starting with '/' should not be treated relative.

**Comment by egoist** [comment]
But we already use `/absolute-path` in vue-router

**Comment by znck** [comment]
Din't know that. I've to revert this.

**Comment by znck** [comment]
I'll resend it.

**Comment by egoist** [comment]
btw, do you have any use cases that need history mode?

**Comment by znck** [comment]
None. URL looks more natural.

**Pull request closed without merging**
